version: "3.8"

services:
  web:
    image: php:8.2-apache
    container_name: apache_server
    restart: always
    ports:
      - "7000:80"
    volumes:
      - ./projects:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "7001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
